project:
  type: website
  output-dir: _site

website:
  title: "拓扑学讲义翻译"
  sidebar:
    style: "floating"
    contents:
      - index.qmd

format:
  html:
    theme: cosmo
    toc: true
    css: custom.css