project:
  type: website
  output-dir: _site

website:
  title: "拓扑学讲义翻译"
  sidebar:
    style: "floating"
    collapse-level: 2
    contents:
      - text: "BASIC TOPOLOGY"
        href: index.qmd
      - text: "4. CATEGORY THEORY"
        href: sec4.qmd
      - text: "5. MAPS BETWEEN AND SUBSETS OF TOPOLOGICAL SPACES"
        href: sec5.qmd
      - text: "6. TOPOLOGICAL SUBSPACES"
        href: sec6.qmd
      - text: "7. LIMITS AND CONVERGENCE"
        href: sec7.qmd
      - text: "8. INDUCED TOPOLOGIES"
        href: sec8.qmd
      - text: "9. ORDERS"
        href: sec9.qmd
      - text: "10. IDENTIFYING AND ATTACHING SPACES"
        href: sec10.qmd
      - text: "11. CONNECTEDNESS"
        href: sec11.qmd
      - text: "12. SEPARATION"
        href: sec12.qmd
      - text: "13. "
        href: sec13.qmd

format:
  html:
    theme: cosmo
    toc: true
    css: custom.css